import { useCallback, useEffect, useState } from 'react'
import { FiEye, FiTrash2, FiX } from 'react-icons/fi'
import { apiRequest } from '../../services/api'

const formatDate = (value) => new Date(value).toLocaleDateString('en-IN', { dateStyle: 'medium', timeZone: 'UTC' })

export default function AdminBookingsPage() {
  const [items, setItems] = useState([]); const [selected, setSelected] = useState(null); const [state, setState] = useState({ loading: true, error: '', notice: '' })
  const load = useCallback(() => apiRequest('/api/admin/bookings').then(({ data }) => { setItems(data); setState({ loading: false, error: '', notice: '' }) }).catch((error) => setState({ loading: false, error: error.message, notice: '' })), [])
  useEffect(() => { load() }, [load])
  const status = async (item, nextStatus) => { try { const { data } = await apiRequest(`/api/admin/bookings/${item.id}/status`, { method: 'PATCH', body: JSON.stringify({ status: nextStatus }) }); setItems(items.map((row) => row.id === data.id ? data : row)); setSelected(selected?.id === data.id ? data : selected); setState({ loading: false, error: '', notice: 'Booking status updated.' }) } catch (error) { setState({ loading: false, error: error.message, notice: '' }) } }
  const remove = async (item) => { if (!window.confirm(`Delete booking for ${item.name}? This cannot be undone.`)) return; try { await apiRequest(`/api/admin/bookings/${item.id}`, { method: 'DELETE' }); setItems(items.filter((row) => row.id !== item.id)); setSelected(null); setState({ loading: false, error: '', notice: 'Booking deleted.' }) } catch (error) { setState({ loading: false, error: error.message, notice: '' }) } }
  return <><header className="admin-header"><div><span className="eyebrow">Management</span><h1>Bookings</h1></div><button type="button" onClick={load}>Refresh</button></header>{state.error && <p className="admin-notice error">{state.error}</p>}{state.notice && <p className="admin-notice">{state.notice}</p>}{state.loading ? <div className="admin-screen-state">Loading bookings…</div> : !items.length ? <p className="empty-state">No bookings found.</p> : <div className="admin-table-wrap"><table><thead><tr><th>Customer</th><th>Phone</th><th>Deal</th><th>Date</th><th>Guests</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.name}</td><td><a href={`tel:${item.phone}`}>{item.phone}</a></td><td>{item.dealType}</td><td>{formatDate(item.bookingDate)}</td><td>{item.guests || '—'}</td><td><b className={`status ${item.status.toLowerCase()}`}>{item.status}</b></td><td>{formatDate(item.createdAt)}</td><td><div className="table-actions"><button type="button" onClick={() => setSelected(item)} aria-label={`View ${item.name}`}><FiEye /></button><select aria-label={`Change status for ${item.name}`} value={item.status} onChange={(event) => status(item, event.target.value)}><option>PENDING</option><option>CONFIRMED</option><option>CANCELLED</option><option>COMPLETED</option></select><button className="danger" type="button" onClick={() => remove(item)} aria-label={`Delete ${item.name}`}><FiTrash2 /></button></div></td></tr>)}</tbody></table></div>}{selected && <div className="admin-modal" role="dialog" aria-modal="true" aria-label="Booking details"><article><button className="modal-close" type="button" onClick={() => setSelected(null)} aria-label="Close booking details"><FiX /></button><h2>Booking details</h2><dl><dt>Name</dt><dd>{selected.name}</dd><dt>Email</dt><dd>{selected.email || 'Not provided'}</dd><dt>Phone</dt><dd><a href={`tel:${selected.phone}`}>{selected.phone}</a></dd><dt>Deal</dt><dd>{selected.dealType}</dd><dt>Date</dt><dd>{formatDate(selected.bookingDate)}</dd><dt>Guests</dt><dd>{selected.guests || 'Not specified'}</dd><dt>Status</dt><dd>{selected.status}</dd><dt>Created</dt><dd>{formatDate(selected.createdAt)}</dd><dt>Message</dt><dd>{selected.message || 'No message'}</dd></dl></article></div>}</>
}
